import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import Provider from "@/lib/Providers";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const notoSans = Noto_Sans_JP({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Kids App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={notoSans.className}>
        <AntdRegistry>
          <Provider>{children}</Provider>
        </AntdRegistry>
      </body>
    </html>
  );
}
